trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    echo "- Restoring -"
    dotnet restore
    echo ""
    echo "- Building -"
    dotnet build
    echo ""
    echo "- Testing -"
    dotnet test
    echo ""
  displayName: 'task1'
