trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    echo | Restoring |
    dotnet restore

    echo | Building |
    dotnet build

    echo | Testing |
    dotnet test
  displayName: 'task1'
