trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Atlassian

steps:
- script: |
      set -euo pipefail

      #hardcoded!
      PROJECT_KEY: "BN"
      FIX_VERSION: "1.2.1"
      RELEASE_TITLE="Release Notes – Version 1.2.1"

      echo "Generating release notes for Jira project $PROJECT_KEY, fixVersion $FIX_VERSION..."

      # ---------------------------
      # Base64 encode credentials
      # ---------------------------
      JIRA_AUTH=$(echo -n "$JIRA_EMAIL:$JIRA_API_TOKEN" | base64)
      CONF_AUTH=$(echo -n "$CONFLUENCE_EMAIL:$CONFLUENCE_API_TOKEN" | base64)

      JQL="project=$PROJECT_KEY AND fixVersion=\"$FIX_VERSION\" ORDER BY issuetype, priority"
      SEARCH_URL="$JIRA_BASE_URL/rest/api/3/search?jql=$(echo $JQL | jq -sRr @uri)&maxResults=1000&fields=key,summary,issuetype"
